### ISSUE TITLE
코드 작성

### ISSUE THREAD

**Issue by Moowonn** [OSS-3-MINTAEK/Recomendataion_Place#1]
chat gpt 사용하면 출처 gpt로 적어두면 될까요??

**Comment by devsher** [comment]
to do list 예외 처리 추가 한 부분을 추가 했습니다. 시간이 있으실 때 한번 확인 해 주시고 이슈 적어 주세요 :)

**Comment by ChoEChoU** [comment]
GPT는 안적어도 될것같아요 :)
