### ISSUE TITLE
새로운 간단한 게임 올렸습니다

### ISSUE THREAD

**Issue by devsher** [OSS-3-MINTAEK/Recomendataion_Place#5]
새로운 간단한 게임 올렸습니다 일단 새로운 파일 하나 생선하고 올려 봤습니다. 다음에 가능하면 to do list 와 같이 합쳐서 하나 파일을 만들어서 놓으면 좋을 것 같습니다.

**Comment by ChoEChoU** [comment]
넵!! 근데 이 레포지토리 말고 to do list 레포지토리에 이슈 올려주세요!!
